version: '3.3'


services:
  bot:
    image: "synedraacus/mud_bot"
    container_name: "mud_bot"
    stop_signal: SIGINT
    restart: always
    environment:
      # No anchor: only three postgres variables are shared between images
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
      - USE_REDIS=True
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PWD=${REDIS_PWD}
    depends_on:
      - postgresql
      - redis~
    networks:
      - tg_bot
  postgresql:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 1337:5432
    networks:
      - tg_bot
  redis:
    image: redis:6.0.20-alpine
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - 1338:8001
      - 1339:6379
    environment:
      - REDIS_ARGS=${REDIS_ARGS}
    networks:
      - tg_bot

networks:
  tg_bot:
    name: tg_bot
    driver: bridge

volumes:
  postgres_data:
  redis_data:
