version: '3.3'


services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: ./Dockerfile
    #restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    restart: always
    env_file:
      - "postgres.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 1337:5432

volumes:
  postgres_data:

networks:
  tg_bot:
    driver: bridge
