version: '3.3'


services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: ./Dockerfile
    #restart: always
    env_file:
      - ".env"
    depends_on:
      - postgresql
      - redis
    networks:
      - tg_bot
  postgresql:
    image: postgres
    restart: always
    env_file:
      - "postgres.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 1337:5432
    networks:
      - tg_bot
  redis:
    # TODO: replace with redis/redis later to decrease image size
    # but this is useful for dev because it gives me a browser interface
    image: redis/redis-stack
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - 1338:8001
    env_file:
      - "redis.env"
    networks:
      - tg_bot

networks:
  tg_bot:
    name: tg_bot
    driver: bridge

volumes:
  postgres_data:
  redis_data:
