name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Run pre-commits
      shell: bash
      run: |
        poetry install
        poetry run pre-commit install
        poetry run pre-commit run -a
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: synedraacus
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: synedraacus/mud_bot:latest
  
