name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: SSH interaction with EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.EC2_HOST}}
          password: ${{secrets.EC2_PASSWORD}}
          username: ubuntu
          script: |
            echo "EXPORTING ENVIRONMENT VARIABLES"
            export BOT_NAME=mud_bot
            export BOT_TOKEN=${{secrets.BOT_TOKEN}}
            export ADMINS=123456,654321
            export USE_REDIS=False
            export POSTGRES_HOST=postgresql
            export POSTGRES_PORT=5432
            export POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
            export POSTGRES_USER=${{secrets.POSTGRES_USER}}
            export POSTGRES_DB=bot_info
            export REDIS_HOST=redis
            export REDIS_PORT=6379
            export REDIS_PWD=${{secrets.REDIS_PWD}}
            export REDIS_ARGS=${{secrets.REDIS_ARGS}}
            cd /home/ubuntu/bot
            echo "REPLACING DOCKER CONTAINER"
            docker compose down
            docker rmi synedraacus/mud_bot:latest
            curl https://raw.githubusercontent.com/SynedraAcus/mud_bot/master/docker-compose.yml >docker-compose.yml            
            docker compose up -d
        
